apiVersion: v1
kind: Service
metadata: 
  name: hello-app-svc
spec:
  selector: 
    name: hello-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer